### ISSUE TITLE
react-native start throws an error

### ISSUE THREAD

**Issue by satvikmaker** [rundmt/react-native-flexbox-grid#1]
Hi, I really wanted to try out Flexbox implementation of Grid. Had a look at your project. Looks cool.
But, when I do-

```
root@me:~/ReactJS/native/react-native-flexbox-grid# react-native start
Command `start` unrecognized. Did you mean to run this inside a react-native project?
```

I get the following error. Why am I getting that? Every other project I am running the same way.

**Comment by rundmt** [comment]
Hi @bozzmob. I'm so sorry about not getting back to you earlier. I stepped away from the project for a couple months and I have finally got back to working on it. I'm glad you want to try out the library.

I've added the package to npm. If you read the new readme you can find basic instructions to get up and running in a react native app.

Please feel free to try it out and let me know if you run into any other issues. 

I will close this issue. As the project no longer involves cloning and running the project.

**Comment by rundmt** [comment]
Also I will be releasing a react native project in a separate repo that will show off some example layouts within the next week or so.
