### ISSUE TITLE
undefined is not an object (evaluating '_react.PropTypes.number') in both Column.js and Row.js

### ISSUE THREAD

**Issue by ghost** [rundmt/react-native-flexbox-grid#15]
Fix: Replace

`import {PropTypes} from 'react';`

with

`import PropTypes from 'prop-types'`

**Comment by cseelus** [comment]
Would you consider merging a PR?

I know there are similar libraries with way more features (like react-native-responsive-grid) that are more active, but this one is imho cleaner and in a good way simpler.

**Comment by rundmt** [comment]
closing because this has been resolved with #17
